dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  - "pypy3"
os:
  - linux
before_script:
  - python -m pip install pip --upgrade
  - export PYTHONHASHSEED=${PYTHONHASHSEED:-${RANDOM}}
  - echo "export PYTHONHASHSEED=${PYTHONHASHSEED}"
  - pip install .[test]
  - pip install codecov
  - export COVERAGE_PROCESS_START=$(pwd)/.coveragerc
  - export PYTEST_ADDOPTS=-v
script:
  - |
    if [ -x "$(command -v black)" ]; then
      black  --target-version py36 --check --diff compyle/
    fi
  - python -m coverage run -m pytest
after_success:
  - coverage report && codecov
